services:
  - type: web
    name: portafolio-api
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: portafolio-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://tu-dominio.vercel.app

databases:
  - name: portafolio-db
    databaseName: portafolio
    user: portafolio_user
    region: oregon
    plan: free
